-- Vector RAG Architecture Migration
-- Enables pgvector extension and creates document_embeddings table for semantic search

-- Enable pgvector extension
create extension if not exists vector;

-- Create document_embeddings table to store vector embeddings of document chunks
create table if not exists document_embeddings (
    id uuid primary key default gen_random_uuid(),
    job_id uuid not null references processing_jobs(id) on delete cascade,
    chunk_text text not null,
    embedding vector(1536) not null, -- text-embedding-3-small uses 1536 dimensions (within HNSW 2000 limit)
    chunk_index integer not null,
    metadata jsonb default '{}'::jsonb, -- Store page number, token count, character position, etc.
    created_at timestamptz not null default timezone('utc'::text, now())
);

-- Create indexes for efficient querying
-- HNSW index for fast similarity search using cosine distance
-- text-embedding-3-small (1536 dims) fits within HNSW's 2000 dimension limit
create index if not exists document_embeddings_embedding_idx 
    on document_embeddings using hnsw (embedding vector_cosine_ops);

-- Index on job_id for filtering by document
create index if not exists document_embeddings_job_id_idx 
    on document_embeddings(job_id);

-- Composite index for ordered retrieval of chunks from a document
create index if not exists document_embeddings_job_id_chunk_index_idx 
    on document_embeddings(job_id, chunk_index);

-- Row Level Security policies
alter table document_embeddings enable row level security;

-- Policy: Users can only access embeddings for their own documents
create policy "Users can select their own document embeddings"
    on document_embeddings
    for select
    using (
        exists (
            select 1 from processing_jobs
            where processing_jobs.id = document_embeddings.job_id
            and processing_jobs.user_id = auth.uid()
        )
    );

-- Policy: Service role can insert embeddings (for worker functions)
create policy "Service role can insert document embeddings"
    on document_embeddings
    for insert
    with check (true);

-- Policy: Service role can update embeddings
create policy "Service role can update document embeddings"
    on document_embeddings
    for update
    using (true)
    with check (true);

-- Policy: Service role can delete embeddings
create policy "Service role can delete document embeddings"
    on document_embeddings
    for delete
    using (true);

-- Add comments for documentation
comment on table document_embeddings is 'Stores vector embeddings of document chunks for semantic similarity search using pgvector';
comment on column document_embeddings.embedding is 'Vector embedding generated by OpenAI text-embedding-3-small (1536 dimensions)';
comment on column document_embeddings.chunk_index is 'Sequential index of the chunk within the document (0-based)';
comment on column document_embeddings.metadata is 'Additional metadata about the chunk: token_count, char_position, page_number, etc.';

-- Function for vector similarity search
-- Returns chunks with similarity scores, ordered by relevance
create or replace function search_document_embeddings(
  query_embedding vector(1536),
  job_ids uuid[] default null,
  similarity_threshold float default 0.7,
  result_limit int default 10
)
returns table (
  id uuid,
  job_id uuid,
  chunk_text text,
  chunk_index int,
  metadata jsonb,
  similarity float,
  file_name text
) as $$
begin
  return query
    select 
      de.id,
      de.job_id,
      de.chunk_text,
      de.chunk_index,
      de.metadata,
      1 - (de.embedding <=> query_embedding) as similarity,
      pj.file_name
    from document_embeddings de
    join processing_jobs pj on de.job_id = pj.id
    where 
      (job_ids is null or de.job_id = any(job_ids))
      and (1 - (de.embedding <=> query_embedding)) >= similarity_threshold
    order by de.embedding <=> query_embedding
    limit result_limit;
end;
$$ language plpgsql security definer;

comment on function search_document_embeddings is 'Performs vector similarity search on document embeddings using cosine distance. Returns chunks ordered by relevance.';

